language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install -n --dev --prefer-source

script: vendor/bin/phpcs --standard=ruleset.xml src && vendor/bin/phpunit --coverage-text
